// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6PZPV5kLGpfiAWEwYpG7ggEiNK_-ckuc',
    appId: '1:603533527008:web:2e95bd902b9390a75d8d85',
    messagingSenderId: '603533527008',
    projectId: 'rydzs-app',
    authDomain: 'rydzs-app.firebaseapp.com',
    storageBucket: 'rydzs-app.appspot.com',
    measurementId: 'G-3SHPTGEMK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKPDbFxjRuTnesyoW-J586fTyPsEStTIA',
    appId: '1:603533527008:android:4c105281b05b7c2b5d8d85',
    messagingSenderId: '603533527008',
    projectId: 'rydzs-app',
    storageBucket: 'rydzs-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzMoulD4qL9-oh2vjyDwL7Qx5KEeMz_LM',
    appId: '1:603533527008:ios:0b8ae8f77bce94e75d8d85',
    messagingSenderId: '603533527008',
    projectId: 'rydzs-app',
    storageBucket: 'rydzs-app.appspot.com',
    androidClientId: '603533527008-6kbqjsud3dmnn591skqqo922533hgcn6.apps.googleusercontent.com',
    iosClientId: '603533527008-5k34etp83fgjg39vnb1jpm9i7ea4qp8f.apps.googleusercontent.com',
    iosBundleId: 'com.ridzs.passenger',
  );

}